### ISSUE TITLE
User input hex values do not change colors

### ISSUE THREAD

**Issue by annamkbenson** [benknight/kuler-colorwheel-with-d3#8]
Hi Ben, 

You project is a great tool for creating color palettes! I noticed, however, that when a use inputs their own hex values, the colors in the palette are not updated. Here is a screen recording of the issue: 

[Screen recording 2022-09-19 11.20.12 AM.webm](https://user-images.githubusercontent.com/108377086/191087522-85580766-d1ad-4d0d-9465-2d41b666ab78.webm)

**Comment by benknight** [comment]
Hey thank a lot for the feedback! I'm glad you enjoy using this.

Since this is a really old project that I mostly just keep around for fun, I'm not really actively maintaining it.

But you're welcome to submit a pull request! Cheers.
